service: resize-function
frameworkVersion: "3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  
package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude:
      - "@aws-sdk/*"
    target: node20
    platform: node
    concurrency: 10

functions:
  resizePhoto:
    handler: src/functions/resizePhoto.handler
    events:
      - httpApi:
          path: /image
          method: POST

